### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by rubytaiki** [rubytaiki/furima-36228#23]
# 自身のフリマアプリのURL 
https://furima-36228.herokuapp.com/

# Basic認証のIDとパスワード
koko
111111 

# 出品者用のメールアドレスとパスワード
koko@gmail.com
111111w

購入者用のメールアドレスとパスワード 
coco@gmail.com
222222w

**Comment by mo1015** [comment]
ご提出ありがとうございます！
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/127627672-ddccd3a3-ff4f-4165-9434-fae2a3e825e3.png)
